"""
Pré-remplit le glossaire de traduction FR → EN (modèle TermTranslation).
Idempotent : ne crée que les termes absents, ne surcharge pas ceux déjà édités.

    python manage.py seed_glossary          # ajoute les manquants
    python manage.py seed_glossary --force  # réécrit aussi les existants
"""
from django.core.management.base import BaseCommand


GLOSSARY = {
                                                    
    'interface': {
        'MON': 'MY',
        'PROFIL': 'PROFILE',
        'Informations personnelles & Performances': 'Personal information & Performance',
        'Changer mot de passe': 'Change password',
        'Identifiant Email': 'Email login',
        'Téléphone': 'Phone',
        'Non renseigné': 'Not provided',
        'Non assigné': 'Not assigned',
        'Déconnexion': 'Log out',
        'Le': 'On',
        'Trimestre': 'Quarter',
        'Votre appréciation': 'Your appraisal',
        'Non notée': 'Not rated',
        'Mesure': 'Action',
                         
        'Analyse & Suivi': 'Analysis & Monitoring',
        'Tableau de bord': 'Dashboard',
        'Agents notés': 'Rated officers',
        'Champs non-renseignés': 'Missing fields',
        'Clients en anomalie': 'Flagged customers',
        'Scoring Clients': 'Customer scoring',
        'Screening KYC ID': 'KYC ID Screening',
        'Notations': 'Ratings',
        'Nouvelle Notation': 'New rating',
        'Historique': 'History',
        'Comptes spécifiques': 'Specific accounts',
        'Administration': 'Administration',
        'Paramétrage Utilisateurs': 'User settings',
        'Règles de Qualité': 'Quality rules',
        'Champs KYC': 'KYC fields',
        'Types de documents': 'Document types',
        'Importation': 'Import',
        'Pilotage': 'Steering',
        'Rappels DATEREV': 'DATEREV reminders',
               
        'Fiabilisation': 'Reliability',
        'Connectez-vous à votre espace': 'Sign in to your workspace',
        'Se connecter': 'Sign in',
        'Assistance technique': 'Technical support',
        'votre@email.com': 'your@email.com',
        'Mot de passe': 'Password',
        'Identifiant': 'Login ID',
                                  
        'STATISTIQUES': 'STATISTICS',
        'BANQUE': 'BANK',
        'PAR AGENT': 'BY OFFICER',
        'Mise à jour': 'Last update',
        'Graphiques': 'Charts',
        'Journalier': 'Daily',
        'Mensuel': 'Monthly',
        'Mensuelle': 'Monthly',
        'Toutes les filiales': 'All subsidiaries',
        'Choisir agent': 'Select officer',
        'Voir taux Agents': 'View officer rates',
        'Voir Taux Banque': 'View bank rates',
        'Aucune donnee disponible': 'No data available',
        'Selectionnez une filiale avec des taux disponibles.': 'Select a subsidiary with available rates.',
        'Aucun agent sélectionné': 'No officer selected',
        'Veuillez choisir un agent dans les filtres pour afficher les données.':
            'Please select an officer in the filters to display the data.',
    },
                            
    'conformite': {
        'Appréciation globale': 'Overall appraisal',
        'Notation Contrôle Permanent': 'Permanent Control rating',
        'Recommandations du Contrôleur': "Controller's recommendations",
        'Complétude': 'Completeness',
        'Qualité': 'Quality',
        'Code exploitant': 'Officer code',
        'Taux de Complétude': 'Completeness rate',
        'Taux de Qualité': 'Quality rate',
        'Taux de completude et de qualite des donnees KYC': 'Completeness and quality rates of KYC data',
        'Qualité des': 'Quality of',
        'données saisies': 'entered data',
        'Évolution taux de complétude - Flux': 'Completeness rate trend – Flow',
        'Taux PP': 'PP rate',
        'Taux PM': 'PM rate',
        'Très Bien': 'Very Good',
        'Bien': 'Good',
        'Passable': 'Fair',
        'Insuffisant': 'Poor',
        "Demande d'explication et décote sur le bonus si motif infondé":
            'Request for explanation and bonus reduction if the grounds are unfounded',
        "Demande d'explication avec sanction forte et décote sur le bonus si motif infondé":
            'Request for explanation with strong sanction and bonus reduction if the grounds are unfounded',
        'Impact positif sur le bonus': 'Positive impact on the bonus',
                       
        'Bon++': 'Good++', 'Bon+': 'Good+', 'Bon-': 'Good-',
        'Moyen++': 'Average++', 'Moyen+': 'Average+', 'Moyen-': 'Average-',
        'Faible++': 'Low++', 'Faible+': 'Low+', 'Faible-': 'Low-',
    },
                                    
    'banque': {
        'Collaborateur': 'Staff member',
        'Agence': 'Branch',
        'Chargé Client': 'Relationship Manager',
        'Directeur Agence': 'Branch Manager',
        'Directeur Réseau': 'Network Director',
        'Conformité': 'Compliance',
        'Conformité Groupe': 'Group Compliance',
        'Contrôle Permanent': 'Permanent Control',
        'Contrôle Permanent Groupe': 'Group Permanent Control',
        'Risques': 'Risk',
        'DAI': 'Internal Audit',
        'DSI': 'IT Department',
        'Portefeuille': 'Portfolio',
        'Filiale': 'Subsidiary',
        'Exploitant': 'Officer',
        'Client': 'Customer',
    },
                   
    'finance': {
        'Taux de complétude': 'Completeness rate',
        'Taux de qualité': 'Quality rate',
        'Taux de conformité': 'Compliance rate',
        'Taux de scoring': 'Scoring rate',
        'Non résident': 'Non-resident',
        'Personne politiquement exposée': 'Politically Exposed Person',
        'Bénéficiaire effectif': 'Ultimate Beneficial Owner',
        'Origine des revenus': 'Source of income',
        'Date de revue': 'Review date',
    },
                                                        
    'general': {
                    
        'Agents': 'Officers', 'notés': 'rated',
        'Consultation des notations par exploitant': 'Officer ratings overview',
        'FLUX': 'FLOW', 'STOCK': 'STOCK', 'Exporter': 'Export', 'Recherche': 'Search',
        'Rechercher un code exploitant': 'Search for an officer code',
        'Aucune notation trouvée': 'No rating found',
        'Aucun exploitant trouvé pour cette recherche.': 'No officer found for this search.',
        'Nom et Prénom': 'Full name', 'Email': 'Email', 'Date notation': 'Rating date',
        'Non calculée': 'Not computed',
                       
        'CLIENTS EN': 'CUSTOMERS WITH', 'ANOMALIE': 'ANOMALY',
        'Clients en anomalie par regle de qualité': 'Flagged customers by quality rule',
        'Regles actives': 'Active rules', 'Anomalies': 'Anomalies', 'Evalues': 'Evaluated',
        'Rechercher une regle, un champ, un parametre...': 'Search a rule, field or parameter...',
        'Toutes agences': 'All branches', 'Tous les exploitants': 'All officers',
        'Filtrer': 'Filter', 'Reset': 'Reset', 'Regles de controle': 'Control rules',
        'Cliquer sur une regle pour ouvrir ses resultats': 'Click a rule to open its results',
        'Resultats de la regle': 'Rule results', 'Criteres de la regle': 'Rule criteria',
        'Precedent': 'Previous', 'Suivant': 'Next', 'Filtre': 'Filter', 'Expl.': 'Off.',
        'Risque': 'Risk', 'Echeance': 'Due date',
                             
        'Scoring': 'Scoring', 'Clients': 'Customers', 'dossiers': 'files',
        'entreprises': 'companies', 'particuliers': 'individuals', 'à traiter': 'to process',
        'Clients Scorés': 'Scored customers', 'Non Scorés': 'Not scored',
        'Non Scorés (Échus)': 'Not scored (Overdue)', 'Voir': 'View',
        'Clients non scores': 'Unscored customers',
        'Aucun resultat pour ces criteres': 'No result for these criteria',
        'Dans 1 an': 'Within 1 year', 'Dans 3 mois': 'Within 3 months',
        'Dans 6 mois': 'Within 6 months', 'Echues': 'Overdue', 'Non planifiees': 'Not scheduled',
        'Sans classe': 'Unclassified', 'Tous exploitants': 'All officers',
        'Tous les risques': 'All risks', 'Toutes periodes': 'All periods',
        'À traiter': 'To process', 'Page': 'Page', 'PRECEDENT': 'PREVIOUS', 'SUIVANT': 'NEXT',
        'Particuliers (PP)': 'Individuals (PP)', 'Entreprises (PM)': 'Companies (PM)',
                           
        'Conforme': 'Compliant', 'Sous seuil': 'Below threshold',
        '(non applicable en mode Groupe)': '(not applicable in Group mode)',
        '(tous si aucun sélectionné)': '(all if none selected)',
        '(toutes si aucune sélectionnée)': '(all if none selected)',
        'Actualiser': 'Refresh', 'Agent': 'Officer', 'Agents évalués': 'Officers assessed',
        'Aucun champ sous le seuil': 'No field below threshold',
        'Aucune donnée disponible': 'No data available',
        'Aucune notation disponible': 'No rating available',
        'Aucune notation trouvée dans ce périmètre': 'No rating found in this scope',
        'Aucune règle qualité disponible.': 'No quality rule available.',
        'Aucune règle sous le seuil': 'No rule below threshold',
        'Champ': 'Field', 'Champs de Complétude à inclure': 'Completeness fields to include',
        'Complétude PM': 'Completeness PM', 'Complétude PP': 'Completeness PP',
        'Complétude des Données': 'Data completeness', 'Configuration': 'Configuration',
        'Conformité par règle — Entreprises': 'Compliance by rule — Companies',
        'Conformité par règle — Particuliers': 'Compliance by rule — Individuals',
        'Date': 'Date', 'Distribution par filiale': 'Distribution by subsidiary',
        'Détails Complétude': 'Completeness details', 'Détails Qualité': 'Quality details',
        'Export': 'Export', 'Flux / Stock': 'Flow / Stock', 'Global': 'Overall',
        'Historique complet': 'Full history', 'Historique des notations': 'Ratings history',
        'Incomplets': 'Incomplete',
        'Les indicateurs agrègent toutes les filiales':
            'Indicators aggregate all subsidiaries',
        'Nombre de notations par filiale': 'Number of ratings by subsidiary', 'Note': 'Rating',
        'PM — Entreprises': 'PM — Companies', 'PP — Particuliers': 'PP — Individuals',
        'Performance des agents notés': 'Rated officers performance',
        'Chargé(s) de compte': 'Account manager(s)',
        "Pourcentage par type d'évaluation": 'Percentage by rating type',
        'Progression': 'Progress', 'Périmètre': 'Scope', 'Qualité PM': 'Quality PM',
        'Qualité PP': 'Quality PP', 'Qualité des Données': 'Data quality',
        'Rapport Filiale': 'Subsidiary report', 'Rapport Groupe': 'Group report',
        'Recommandations': 'Recommendations', 'Règle': 'Rule',
        'Règles Qualité à inclure': 'Quality rules to include',
        'Répartition Globale': 'Overall breakdown', "Taux d'excellence": 'Excellence rate',
        'Taux par champ — Entreprises': 'Rate by field — Companies',
        'Taux par champ — Particuliers': 'Rate by field — Individuals',
        'Taux': 'Rate', 'Total évaluations': 'Total assessments', 'Total': 'Total',
        'Tout ✓': 'All ✓', 'Aucun ✗': 'None ✗', 'Type': 'Type',
        'Évaluations des agents enregistrées': 'Recorded officer assessments',
        'Évalué par': 'Assessed by',
        '⚙ Sélection des champs de complétude pour le rapport PDF / PPTX':
            '⚙ Select completeness fields for the PDF / PPTX report',
        '⚙ Sélection des règles de qualité pour le rapport PDF / PPTX':
            '⚙ Select quality rules for the PDF / PPTX report',
        '💻 Générer PPTX': '💻 Generate PPTX', '📈 Générer Excel': '📈 Generate Excel',
        '📊 Générer PDF': '📊 Generate PDF',
    },
}

                                                                                  
GLOSSARY['pages_2026_07'] = {
    '& RECOMMANDATIONS': '& RECOMMENDATIONS',
    '&laquo; Première': '&laquo; First',
    'Dernière &raquo;': 'Last &raquo;',
    "(*) Date de la prochaine revue de conformite.": '(*) Date of the next compliance review.',
    "(*) Date limite recommandée pour effectuer le renouvellement du scoring de conformité.":
        '(*) Recommended deadline to renew the compliance scoring.',
    "(*) Date prévisionnelle à laquelle le scoring du client doit être obligatoirement réévalué.":
        "(*) Expected date by which the client's scoring must be re-assessed.",
    '(c) BANK OF AFRICA - Plateforme de Fiabilisation KYC v2 - Page':
        '(c) BANK OF AFRICA - KYC Data Quality Platform v2 - Page',
    '-- Choisir un agent --': '-- Select an agent --',
    '-- Globale (Groupe) --': '-- Global (Group) --',
    'A completer': 'To complete',
    'A completer / A modifier': 'To complete / To update',
    'A modifier': 'To update',
    'AAAA-mm-jj': 'YYYY-mm-dd',
    'AGENTS & NOTATION.': 'AGENTS & RATING.',
    'AVANCER': 'FORWARD',
    'RECULER': 'BACK',
    'Accueil': 'Home',
    'Accès': 'Access',
    'Accès Restreint': 'Restricted Access',
    'Accès Verrouillé | KYC': 'Access Locked | KYC',
    'Accès temporairement verrouillé': 'Access temporarily locked',
    'Action': 'Action',
    'Actions': 'Actions',
    'Actions de gestion': 'Management actions',
    'Active': 'Active',
    'Activer en Production': 'Enable in Production',
    'Activer la Règle': 'Enable Rule',
    'Adresse': 'Address',
    'Adresse email de test': 'Test email address',
    'Affichage des champs configurés :': 'Configured fields display:',
    'Afficher': 'Show',
    'Afficher et modifier les configurations appliquees': 'View and edit applied configurations',
    'Afficher non renseignes': 'Show missing values',
    'Agencelib': 'Branch name',
    'Ajouter Logique': 'Add Logic',
    'Ajouter conditions': 'Add conditions',
    'Ajouter un type de document': 'Add a document type',
    "Ajustement de l'algorithme de contrôle qualité": 'Quality control algorithm tuning',
    'Alerte qualite et detection automatique': 'Quality alert and automatic detection',
    'Alertes': 'Alerts',
    'Analyse Risque': 'Risk Analysis',
    'Analyses': 'Analytics',
    'Annuel': 'Yearly',
    'Annuelle': 'Yearly',
    'Annuler': 'Cancel',
    'Anomalie KYC': 'KYC anomaly',
    'Appliquer': 'Apply',
    'Appliquer à toutes les filiales': 'Apply to all subsidiaries',
    'Appréciation Stock': 'Stock Assessment',
    'Archive complète et traçabilité des évaluations': 'Full archive and traceability of assessments',
    "Attention : les imports peuvent être lourds. Vérifiez les fichiers et l’encodage avant exécution. Consultez":
        'Warning: imports can be heavy. Check files and encoding before running. See',
    'Attention, ce processus peut prendre du temps selon le nombre de documents charges et le volume de clients KYC PP a analyser.':
        'Warning: this process may take time depending on the number of uploaded documents and the volume of KYC PP clients to analyse.',
    'Attribution et mise à jour des notes agents': 'Assignment and update of agent ratings',
    'Au moins un de ces champs doit etre vide.': 'At least one of these fields must be empty.',
    'Aucun agent trouvé.': 'No agent found.',
    'Aucun calcul lance': 'No computation started',
    "Aucun champ standard n'a ete reconnu automatiquement. Consultez le texte brut ci-dessous.":
        'No standard field was recognised automatically. See the raw text below.',
    'Aucun champ standard reconnu automatiquement.': 'No standard field recognised automatically.',
    'Aucun client en anomalie pour cette regle.': 'No client in anomaly for this rule.',
    'Aucun client non score pour ce perimetre.': 'No unscored client in this scope.',
    'Aucun client trouvé avec ces filtres.': 'No client found with these filters.',
    'Aucun connecté': 'None connected',
    'Aucun critere detaille disponible.': 'No detailed criterion available.',
    'Aucun document trouve.': 'No document found.',
    'Aucun dossier trouvé pour ces critères.': 'No record found for these criteria.',
    'Aucun email': 'No email',
    'Aucun exploitant avec DATEREV dépassée ou proche.': 'No account officer with DATEREV overdue or upcoming.',
    'Aucun exploitant trouvé.': 'No account officer found.',
    'Aucun historique disponible pour ce code': 'No history available for this code',
    'Aucun historique disponible pour le moment': 'No history available yet',
    'Aucun import enregistré.': 'No import recorded.',
    'Aucun log disponible.': 'No log available.',
    "Aucun lot en attente. Les lots en cours ou termines sont visibles dans l'onglet Suivi.":
        'No pending batch. Running or completed batches are visible in the Tracking tab.',
    'Aucun mot-clé': 'No keyword',
    'Aucun rapprochement lance pour le moment.': 'No matching started yet.',
    'Aucun resultat exploitable pour ce rapprochement.': 'No usable result for this matching.',
    'Aucun resultat global disponible.': 'No global result available.',
    'Aucun résident étranger trouvé.': 'No foreign resident found.',
    'Aucun type de document configuré. Utilisez le formulaire pour en ajouter.':
        'No document type configured. Use the form to add one.',
    'Aucune': 'None',
    'Aucune Règle Configurée': 'No Rule Configured',
    'Aucune anomalie trouvée': 'No anomaly found',
    'Aucune configuration SMTP active. &nbsp;': 'No active SMTP configuration. &nbsp;',
    'Aucune correspondance exploitable detectee.': 'No usable match detected.',
    "Aucune donnee d'audit disponible": 'No audit data available',
    "Aucune donnee d'audit disponible.": 'No audit data available.',
    'Aucune donnee trouvee.': 'No data found.',
    'Aucune donnée disponible pour les critères sélectionnés.': 'No data available for the selected criteria.',
    'Aucune donnée disponible.': 'No data available.',
    'Aucune donnée trouvée.': 'No data found.',
    'Aucune regle active trouvee.': 'No active rule found.',
    'Aucune revue planifiée pour cette période.': 'No review scheduled for this period.',
    'Audit': 'Audit',
    'Audit des Controles - KYC Portal': 'Controls Audit - KYC Portal',
    'Auteur': 'Author',
    'Base': 'Base',
    'Base documentaire': 'Document repository',
    'Bibliothèque des Règles': 'Rule Library',
    'Bienvenue': 'Welcome',
    'CHAMPS NON RENSEIGNES.': 'MISSING FIELDS.',
    'Calcul en cours': 'Computation in progress',
    'Calcul...': 'Computing...',
    'Catégories configurées': 'Configured categories',
    "Ce rapprochement est en echec. Vous pouvez relancer le lot depuis l'onglet Charger.":
        'This matching failed. You can relaunch the batch from the Upload tab.',
    "Cette jauge est une estimation. Le resultat s'affichera automatiquement des que le serveur aura termine.":
        'This gauge is an estimate. The result will appear automatically once the server has finished.',
    "Champ d'exclusion": 'Exclusion field',
    'Champs critiques, exclusions et calcul PASS': 'Critical fields, exclusions and PASS computation',
    'Champs detectes': 'Detected fields',
    'Champs en anomalie': 'Fields in anomaly',
    'Champs manquants': 'Missing fields',
    'Champs vides dans KYC PP mais presents dans les documents charges':
        'Fields empty in KYC PP but present in uploaded documents',
    'Changer votre mot de passe.': 'Change your password.',
    'Chargement...': 'Loading...',
    'Charger': 'Upload',
    'Charger des documents': 'Upload documents',
    'Charger le lot': 'Upload batch',
    'Choisir Filiale': 'Select Subsidiary',
    'Choisir quel type de document utiliser pour completer ou modifier chaque champ KYC.':
        'Choose which document type to use to complete or update each KYC field.',
    'Chronologie': 'Timeline',
    'Cible': 'Target',
    'Cible 100%': 'Target 100%',
    'Classe de risque': 'Risk class',
    'Clients a afficher': 'Clients to display',
    'Clients domiciliés hors du territoire': 'Clients domiciled outside the territory',
    'Clients non conformes': 'Non-compliant clients',
    'Clients sans classe': 'Clients without risk class',
    'Clients trouves': 'Clients found',
    'Clients à réviser': 'Clients to review',
    'Codape': 'Codape',
    'Code': 'Code',
    'Code Expl.': 'Officer code',
    'Code Exploitant': 'Officer code',
    'Code Exploitant :': 'Officer code:',
    'Code technique': 'Technical code',
    'Code...': 'Code...',
    'Colonnes visibles': 'Visible columns',
    'Compte': 'Account',
    'Comptes': 'Accounts',
    'Comptes Non-Résidents': 'Non-Resident Accounts',
    'Comptes en devise': 'Foreign currency accounts',
    'Comptes en devise à fiabiliser': 'Foreign currency accounts to remediate',
    'Conditions Logiques': 'Logical Conditions',
    'Conditions logiques': 'Logical conditions',
    "Configurer dans l'admin →": 'Configure in admin →',
    'Confirmer': 'Confirm',
    'Conformes': 'Compliant',
    'Conformité Totale': 'Full Compliance',
    'Conformité moyenne': 'Average compliance',
    'Connexion': 'Sign in',
    'Connexion | KYC': 'Sign in | KYC',
    'Connexion | KYC Portal v3.0': 'Sign in | KYC Portal v3.0',
    "Correspondance par numero d'identite, date de naissance, date de validité du document d'identité et la nationalité.":
        'Matching by ID number, date of birth, ID document expiry date and nationality.',
    'Creation': 'Creation',
    'Création': 'Creation',
    'Création de règle': 'Rule creation',
    'Créer règle': 'Create rule',
    'Créer type de documents': 'Create document type',
    'Créer un compte': 'Create an account',
    'Créer une catégorie': 'Create a category',
    'Critique': 'Critical',
    'Date & Heure': 'Date & Time',
    'Date Ouv.': 'Open. date',
    'Date Ouverture': 'Opening date',
    "Date d'arrêté": 'Cut-off date',
    'Date de Notation': 'Rating date',
    'Date de notation': 'Rating date',
    'Daterev, Anomalies, TauxEvolution_filiale et TauxEvolution via':
        'Daterev, Anomalies, TauxEvolution_filiale and TauxEvolution via',
    'Demarre le': 'Started on',
    'Derniere mise a jour': 'Last update',
    'Derniers resultats filiale': 'Latest subsidiary results',
    'Dernière notation': 'Last rating',
    'Description': 'Description',
    'Detail document': 'Document detail',
    'Details': 'Details',
    'Details des Modifications': 'Change details',
    'Devise (PM)': 'Currency (LE)',
    'Devise (PP)': 'Currency (IND)',
    'Document': 'Document',
    'Documents': 'Documents',
    'Documents a verifier': 'Documents to check',
    'Documents du lot': 'Batch documents',
    'Documents extraits': 'Extracted documents',
    'Données': 'Data',
    'Données KYC': 'KYC data',
    'Dépassée': 'Overdue',
    'Déposer le CSV ici': 'Drop the CSV here',
    'Détail': 'Detail',
    'Détection des incohérences de données (Âge, EER, CIN)': 'Data inconsistency detection (Age, EER, CIN)',
    'ENTREPRISES (PM)': 'LEGAL ENTITIES (LE)',
    'Echec': 'Failed',
    'En Ligne': 'Online',
    'En cours': 'In progress',
    'Enregistrer': 'Save',
    "Enregistrer l'utilisateur": 'Save user',
    'Enregistrer la notation': 'Save rating',
    'Enregistrer les choix': 'Save choices',
    'Enregistrer les modifications': 'Save changes',
    'Envoyer': 'Send',
    'Envoyer le test': 'Send test',
    'Envoyer rappels': 'Send reminders',
    'Erreur de saisie détectée.': 'Input error detected.',
    'Etat': 'Status',
    'Evolution taux de completude PM': 'LE completeness rate trend',
    'Evolution taux de completude PP': 'IND completeness rate trend',
    'Ex: MINEUR, ETUDIANT...': 'E.g.: MINOR, STUDENT...',
    'Ex: PERMIS, CONDUITE, LICENCE, CATEGORIE': 'E.g.: PERMIT, DRIVING, LICENCE, CATEGORY',
    'Ex: Permis de conduire': "E.g.: Driver's licence",
    'Ex: Stock CNI agence Dakar': 'E.g.: ID card stock Dakar branch',
    'Ex: permis_conduire': 'E.g.: driving_licence',
    'Excel': 'Excel',
    'Expiration': 'Expiry',
    'Exploit.': 'Officer',
    'Exploitants': 'Account officers',
    'Exporter Anomalies': 'Export Anomalies',
    'Exporter CSV': 'Export CSV',
    'Exporter Excel': 'Export Excel',
    'Exporter PDF': 'Export PDF',
    'Exporter la regle': 'Export rule',
    'Expression a exclure': 'Expression to exclude',
    'Extraction documentaire et rapprochement KYC PP': 'Document extraction and KYC IND matching',
    "Exécuter l'importation": 'Run import',
    'FIABILISATION KYC': 'KYC DATA QUALITY',
    'Fenêtre': 'Window',
    'Fermer': 'Close',
    'Fiabilité PM': 'LE reliability',
    'Fiabilité PP': 'IND reliability',
    'Fichier': 'File',
    'Fichier simple, import multiple, archive ZIP ou PDF groupe': 'Single file, multi-import, ZIP archive or grouped PDF',
    'Fichier(s) a charger': 'File(s) to upload',
    'Fichiers charges avec succes': 'Files uploaded successfully',
    'Fichiers ou ZIP': 'Files or ZIP',
    'Filiale / Pays': 'Subsidiary / Country',
    'Filiale :': 'Subsidiary:',
    'Filiale cible :': 'Target subsidiary:',
    'Filiale(s) concernee(s)': 'Subsidiary(ies) concerned',
    'Filiales Impactées': 'Impacted subsidiaries',
    'Filiales choisies': 'Selected subsidiaries',
    'Filiales ciblees': 'Targeted subsidiaries',
    'Flux': 'Flow',
    'Gestion des comptes utilisateurs': 'User account management',
    'Gestion des règles de contrôle qualité KYC': 'KYC quality control rule management',
    'Global / Par défaut': 'Global / Default',
    'Hebdomadaire': 'Weekly',
    "Historique d'": 'History of ',
    'Historique des connexions': 'Login history',
    'INSCRIRE UN UTILISATEUR': 'REGISTER A USER',
    'Identifiant unique. Caractères alphanumériques et underscores uniquement.':
        'Unique identifier. Alphanumeric characters and underscores only.',
    'Identifier': 'Identify',
    'Import': 'Import',
    'Import Daterev / Anomalies / Taux (Filiales + Évolution)': 'Import Daterev / Anomalies / Rates (Subsidiaries + Trend)',
    'Import KYC (PP / PM)': 'KYC Import (IND / LE)',
    'Inactive': 'Inactive',
    'Indexation': 'Indexing',
    "Informations de l'agent :": 'Agent information:',
    'Inscription': 'Registration',
    'Jour': 'Day',
    'Journal': 'Log',
    'KYC Portal v3.0 | BOA Group': 'KYC Portal v3.0 | BOA Group',
    'LISTE DES AGENTS.': 'AGENT LIST.',
    'LISTE DES règles': 'RULE LIST',
    'La modale montre PP et PM pour la filiale choisie': 'The modal shows IND and LE for the selected subsidiary',
    'La progression se met a jour automatiquement toutes les deux secondes.':
        'Progress refreshes automatically every two seconds.',
    'La regle filiale prime sur la regle globale.': 'The subsidiary rule overrides the global rule.',
    'Lance l’import PP/PM. Les CSV doivent être dans': 'Runs the IND/LE import. CSV files must be in',
    'Lancer': 'Run',
    'Lancer Import Daterev / Anomalies / Taux': 'Run Daterev / Anomalies / Rates import',
    'Lancer Import KYC': 'Run KYC import',
    'Lancer calcul': 'Run computation',
    'Lancer le rapprochement': 'Run matching',
    'Lancer les correspondances du lot': 'Run batch matching',
    'Le calcul peut parcourir plusieurs milliers de documents et clients. Lancez-le uniquement apres avoir filtre un lot ou une recherche.':
        'The computation may scan thousands of documents and clients. Run it only after filtering a batch or a search.',
    "Les documents doivent contenir un numero d'identite deja present dans KYC PP, ou le code client dans le nom du fichier/lot.":
        'Documents must contain an ID number already present in KYC PP, or the client code in the file/batch name.',
    'Les documents et les correspondances affiches sont limites a ce lot.':
        'The displayed documents and matches are limited to this batch.',
    "Les variables ci-dessous s'adaptent selon les parametres de la filiale choisie.":
        'The variables below adapt to the parameters of the selected subsidiary.',
    'Lib. Agence': 'Branch name',
    'Lib. agence': 'Branch name',
    'Libellé': 'Label',
    'Libellé affiché': 'Displayed label',
    'Lieu naissance': 'Place of birth',
    'Logique de la regle :': 'Rule logic:',
    "Logs d'Audit": 'Audit Logs',
    "Logs d'exécution": 'Execution logs',
    'Logs de tracabilite complete du systeme': 'Full system traceability logs',
    'Lost password?': 'Lost password?',
    'Lot': 'Batch',
    'Lot / Perimetre': 'Batch / Scope',
    'Lot charge avec succes': 'Batch uploaded successfully',
    'Lots charges mais pas encore lances en rapprochement.': 'Batches uploaded but matching not started yet.',
    'Lots en attente': 'Pending batches',
    'Massif': 'Bulk',
    "Merci de patienter pendant l'analyse.": 'Please wait while the analysis runs.',
    'Mettre à jour': 'Update',
    'Mise à jour de vos accès personnels': 'Update of your personal credentials',
    'Mise à jour mot de passe': 'Password update',
    "Mode d'import": 'Import mode',
    'Modification': 'Update',
    'Modification de la': 'Editing',
    'Modification des habilitations et informations': 'Editing permissions and information',
    'Modifier': 'Edit',
    'Modifier infos': 'Edit info',
    'Modifier le mot de passe': 'Change password',
    'Modifier les informations': 'Edit information',
    'Modifier mon profil.': 'Edit my profile.',
    'Modèle requis': 'Template required',
    'Mon profil': 'My profile',
    'Mots ou phrases séparés par des virgules.': 'Words or phrases separated by commas.',
    'Mots-clés de reconnaissance': 'Recognition keywords',
    'NON ASSIGNÉ': 'UNASSIGNED',
    'NOTATION DES AGENTS.': 'AGENT RATING.',
    'Naissance': 'Birth',
    'Nationalite': 'Nationality',
    'Navigation': 'Navigation',
    'Niveau Risque': 'Risk level',
    'Noeud': 'Node',
    'Noeud Logique': 'Logic node',
    'Nom': 'Name',
    'Nom & Prénom': 'Full name',
    'Nom Agent': 'Agent name',
    'Nom du lot': 'Batch name',
    "Nom lisible par l'utilisateur.": 'User-readable name.',
    'Nom, numero, nationalite...': 'Name, number, nationality...',
    "Nombre d'occurrences de mots-clés nécessaires pour classer le document.":
        'Number of keyword occurrences required to classify the document.',
    'Non Conformes': 'Non-compliant',
    'Non trouvé': 'Not found',
    'Non-Résidents': 'Non-residents',
    'Notation': 'Rating',
    'Note Qualité': 'Quality score',
    'Note actuelle': 'Current score',
    'Noter': 'Rate',
    "Noter l'agent": 'Rate agent',
    'Notification': 'Notification',
    'Nouveaux identifiants requis': 'New credentials required',
    'Nouvelle règle': 'New rule',
    'Num Cin': 'ID number',
    'Numero doc.': 'Doc. number',
    'Objectif Groupe': 'Group target',
    'Operateur': 'Operator',
    'Opérationnelles': 'Operational',
    'Origine Revenu': 'Income source',
    'Ou cliquez ici pour changer votre mot de passe.': 'Or click here to change your password.',
    'PARTICULIERS (PP)': 'INDIVIDUALS (IND)',
    'PDF groupe': 'Grouped PDF',
    'PDF, JPG, PNG, TIFF, TXT ou ZIP. Selection multiple autorisee.': 'PDF, JPG, PNG, TIFF, TXT or ZIP. Multiple selection allowed.',
    'PDF, JPG, PNG, TIFF, TXT, ZIP': 'PDF, JPG, PNG, TIFF, TXT, ZIP',
    'PLATEFORME DE NOTATION': 'RATING PLATFORM',
    'PLATEFORME FIABILISATION KYC': 'KYC DATA QUALITY PLATFORM',
    'PPE non classée à risque élevé :': 'PEP not classified as high risk:',
    'PRÉC.': 'PREV.',
    'PRÉCÉDENT': 'PREVIOUS',
    'SUIV.': 'NEXT',
    "Page d'administration des imports KYC": 'KYC import administration page',
    "Page d'administration des utilisateurs": 'User administration page',
    "Page de création de nouvel utilisateur": 'New user creation page',
    'Page(s)': 'Page(s)',
    'Pages par document': 'Pages per document',
    'Parametrage': 'Settings',
    'Paramètrage des règles de Contrôle': 'Control rule settings',
    'Paramètres': 'Settings',
    'Paramètres de Base': 'Basic settings',
    'Paramétrage': 'Settings',
    'Paramétrage |': 'Settings |',
    'Pays Nais': 'Country of birth',
    'Pays Resid': 'Country of residence',
    'Performance': 'Performance',
    'Perimetre': 'Scope',
    'Periode': 'Period',
    'Personnes': 'Persons',
    'Personnes connectees': 'Connected users',
    'Plateforme KYC': 'KYC Platform',
    'Plateforme KYC Test V0.2': 'KYC Platform Test V0.2',
    'Plateforme v3.0': 'Platform v3.0',
    'Please login to see this page.': 'Please login to see this page.',
    'Plus tard': 'Later',
    'Politiquement Exposées (PPE)': 'Politically Exposed Persons (PEP)',
    'Pour charger un document, plusieurs fichiers separes ou une archive de plusieuers pieces.':
        'To upload one document, several separate files, or an archive of multiple items.',
    'Pour rechercher un agent, veuillez renseigner son code exploitant.':
        'To search for an agent, please enter their officer code.',
    "Pour un seul PDF contenant plusieurs documents d'identite.": 'For a single PDF containing several identity documents.',
    'Prenom': 'First name',
    'Preparation': 'Preparation',
    'Prochaine Date Revue (*)': 'Next review date (*)',
    'Prochaine date revue': 'Next review date',
    'Prochaine date revue (Scoring)': 'Next review date (DATEREV)',
    'Profession': 'Occupation',
    'Progression estimee': 'Estimated progress',
    'Précédent': 'Previous',
    'Précédente': 'Previous',
    'Prénom': 'First name',
    'Purger TauxEvolution avant import': 'Purge TauxEvolution before import',
    'Périmètre Filiale': 'Subsidiary scope',
    'Période': 'Period',
    'Quotidienne': 'Daily',
    'RAPPELS': 'REMINDERS',
    'RESULTAT': 'RESULT',
    'RETOUR RÉPERTOIRE': 'BACK TO DIRECTORY',
    'REVUE SCORING': 'SCORING REVIEW',
    'Racine Client': 'Client root',
    'Rapport de complétude KYC': 'KYC completeness report',
    'Rapports de Complétude &amp; Qualité — PDF &amp; PPTX': 'Completeness &amp; Quality Reports — PDF &amp; PPTX',
    'Rapprochement KYC PP en cours': 'KYC IND matching in progress',
    'Rapprochement global KYC PP': 'Global KYC IND matching',
    'Rapprochement non lance.': 'Matching not started.',
    'Recherche par lot, type et champs extraits': 'Search by batch, type and extracted fields',
    'Rechercher': 'Search',
    'Rechercher par Code Exploitant...': 'Search by officer code...',
    'Rechercher un agent': 'Search for an agent',
    'Rechercher un collaborateur...': 'Search for a staff member...',
    'Recommandation / Feedback': 'Recommendation / Feedback',
    'Regle': 'Rule',
    'Regles PP et PM appliquees a cette filiale': 'IND and LE rules applied to this subsidiary',
    'Regles de Controle Qualite KYC': 'KYC Quality Control Rules',
    "Resultat d'analyse": 'Analysis result',
    'Resultats': 'Results',
    'Resultats de rapprochement': 'Matching results',
    'Resultats de rapprochement KYC PP': 'KYC IND matching results',
    'Retour': 'Back',
    'Retour au lot': 'Back to batch',
    'Retour aux resultats du lot': 'Back to batch results',
    'Retour à la page de connexion': 'Back to the sign-in page',
    "Revenir à l'accueil &rarr;": 'Back to home &rarr;',
    'Revue': 'Review',
    'Revue KYC — portefeuilles à échéance': 'KYC review — portfolios reaching due date',
    'Revue Scoring': 'Scoring review',
    'Revue scoring': 'Scoring review',
    'Règles actives': 'Active rules',
    'Régles de': 'Rules of',
    'Réinitialiser le mot de passe': 'Reset password',
    'Réinitialiser les filtres': 'Reset filters',
    "Répertoire complet et gestion des privilèges d'accès": 'Full directory and access privilege management',
    "S'applique aux particuliers (PP) ou aux entreprises (PM).": 'Applies to individuals (IND) or legal entities (LE).',
    'SANS CLASSE': 'NO RISK CLASS',
    'SCREENING': 'SCREENING',
    'SÉCURITÉ': 'SECURITY',
    'Saisie des identifiants': 'Credential entry',
    'Saisir le code expoloitant du collaborateur pour le noter ou modifier sa notation':
        "Enter the staff member's officer code to rate them or update their rating",
    'Salaire': 'Salary',
    'Sans paramètre': 'No parameter',
    'Score Global': 'Overall score',
    'Score de détection minimum': 'Minimum detection score',
    'Scoring PPE': 'PEP scoring',
    'Segment cible': 'Target segment',
    "Selectionnez un agent pour afficher l'historique.": 'Select an agent to display the history.',
    'Selectionnez un agent pour afficher les graphiques.': 'Select an agent to display the charts.',
    'Sessions Actives': 'Active sessions',
    'Seuil (%)': 'Threshold (%)',
    'Seuil de score': 'Score threshold',
    'Sources documentaires par champ': 'Document sources per field',
    'Sources par champ': 'Sources per field',
    'Stats Agents': 'Agent stats',
    'Statut': 'Status',
    'Stock': 'Stock',
    'Stock Entreprises': 'Legal entity stock',
    'Stock KYC': 'KYC stock',
    'Stock Particuliers': 'Individual stock',
    'Suivante': 'Next',
    'Suivi': 'Tracking',
    'Suivi & Logs': 'Tracking & Logs',
    "Suivi des dates d'anniversaire de scoring": 'Tracking of scoring anniversary dates',
    'Suivi des données manquantes des PPE': 'Tracking of missing PEP data',
    'Suivi des rapprochements': 'Matching tracking',
    'Suivre le rapprochement': 'Track matching',
    'Superadmin': 'Superadmin',
    'Suppression': 'Deletion',
    'Supprimer': 'Delete',
    'Supprimer Noeud': 'Delete node',
    'Surveillance des dates de revue scoring & classe de risque': 'Monitoring of scoring review dates & risk class',
    'Sécurité': 'Security',
    'Sécurité Système': 'System security',
    'Tableau et export Excel.': 'Table and Excel export.',
    'Taux correspondance': 'Match rate',
    "Taux d'Évolution": 'Growth rate',
    'Taux de Scoring': 'Scoring rate',
    'Taux de complétude et de qualité des données KYC': 'KYC data completeness and quality rates',
    'Taux de conformite': 'Compliance rate',
    'Temps restant': 'Time remaining',
    'Terminer le Noeud': 'Finish node',
    'Tester SMTP': 'Test SMTP',
    'Tester la configuration SMTP': 'Test SMTP configuration',
    'Texte extrait': 'Extracted text',
    'Total Anomalies': 'Total anomalies',
    'Total Règles': 'Total rules',
    'Tous': 'All',
    'Tous documents': 'All documents',
    "Tous les clients de votre périmètre disposent d'une classification de risque valide.":
        'All clients in your scope have a valid risk classification.',
    'Tous les gestionnaires': 'All managers',
    'Tous les lots': 'All batches',
    'Tout lancer': 'Run all',
    'Toute échéance': 'Any due date',
    'Toutes': 'All',
    'Toutes filiales': 'All subsidiaries',
    'Toutes les PPE sont à risque élevé': 'All PEPs are high risk',
    'Toutes les agences': 'All branches',
    'Toutes les périodes': 'All periods',
    'Toutes les règles': 'All rules',
    'Traitement en cours': 'Processing',
    'Traitement selectionne': 'Selected processing',
    'Traitements en arriere-plan, progression et acces aux resultats':
        'Background processing, progress and access to results',
    'Type Dossier': 'Record type',
    'Type de client': 'Client type',
    'Type de document': 'Document type',
    'Type de rapport': 'Report type',
    'Types de': 'Types of',
    "Types de documents &amp; Règles d'apprentissage OCR": 'Document types &amp; OCR learning rules',
    'Télécharger': 'Download',
    "Télécharger l'historique complet": 'Download full history',
    'Télécharger le CSV': 'Download CSV',
    "Un email de test sera envoyé via la configuration SMTP enregistrée dans l'admin.":
        'A test email will be sent using the SMTP configuration saved in the admin.',
    'Utile uniquement pour un PDF groupe : 1 page par piece, ou 2 en recto-verso.':
        'Only useful for a grouped PDF: 1 page per item, or 2 for two-sided.',
    'Utilisateur': 'User',
    'Utilisateurs': 'Users',
    "Utilisez exclusivement le fichier modèle téléchargé ci-dessus pour garantir l'importation.":
        'Use only the template file downloaded above to guarantee the import.',
    'Utilisez le scroll horizontal pour voir toutes les colonnes': 'Use horizontal scrolling to see all columns',
    'Valider': 'Validate',
    'Validité Cin': 'ID validity',
    'Version 3.0': 'Version 3.0',
    "Veuillez rentrer le code exploitant EXPL d'un agent.": "Please enter an agent's EXPL officer code.",
    'Veuillez sélectionner un agent pour les données Stock': 'Please select an agent for Stock data',
    'Voir Extractions': 'View extractions',
    'Voir le fichier': 'View file',
    'Voir les details': 'View details',
    'Voir les resultats du lot': 'View batch results',
    'Voir resultats': 'View results',
    'Voir tous les lots': 'View all batches',
    'Volume': 'Volume',
    'Votre espace de conformité attend ses premières instructions.':
        'Your compliance workspace awaits its first instructions.',
    'Voulez-vous lancer le rapprochement maintenant ?': 'Do you want to run the matching now?',
    "Vous n'êtes pas autorisé à consulter cette page.": 'You are not allowed to view this page.',
    "Vous pouvez lancer le rapprochement maintenant ou le retrouver plus tard depuis l'onglet Suivi.":
        'You can run the matching now or find it later in the Tracking tab.',
    'Vue Globale': 'Global view',
    "Vue d'ensemble": 'Overview',
    "Your account doesn't have access to this page. To proceed, please login with an account that has access.":
        "Your account doesn't have access to this page. To proceed, please login with an account that has access.",
    "Your username and password didn't match. Please try again.":
        "Your username and password didn't match. Please try again.",
    'champs KYC': 'KYC fields',
    'completude KYC': 'KYC completeness',
    'des Notations': 'of Ratings',
    'documents': 'documents',
    'en cas d’erreur.': 'in case of error.',
    'jours': 'days',
    'sans-classe de risque': 'without risk class',
    '| COMPTE': '| ACCOUNT',
    '| DATEREV': '| DATEREV',
    'Âge': 'Age',
    'Échues (Auj.)': 'Due (today)',
    'Échues (à ce jour)': 'Due (to date)',
    'Échéance': 'Due date',
    'Éditer': 'Edit',
    'Évaluer un Collaborateur': 'Rate a staff member',
    'Évolution': 'Trend',
    'Évolution taux de complétude': 'Completeness rate trend',
    'Évolution taux de complétude - Stock': 'Completeness rate trend - Stock',
    'à fiabiliser': 'to remediate',
    '— Toutes les filiales —': '— All subsidiaries —',
    '← Retour à la liste': '← Back to list',
    '✕ Réinitialiser': '✕ Reset',
}

                                                               
GLOSSARY['kpi_2026_07'] = {
    'Répartition par Risque': 'Breakdown by Risk',
    'Clients PPE par classe de risque': 'PEP clients by risk class',
    'PPE Incomplets': 'Incomplete PEPs',
    'Dossiers avec données manquantes': 'Records with missing data',
    'Taux de conformité': 'Compliance rate',
    'Dossiers complets / total': 'Complete records / total',
    'Répartition par Pays': 'Breakdown by Country',
    'Clients non résidents PP': 'Non-resident IND clients',
    'PP Incomplets': 'Incomplete IND records',
    'Taux de complétude': 'Completeness rate',
    'Clients non résidents PM': 'Non-resident LE clients',
    'PM Incomplets': 'Incomplete LE records',
    'Répartition par Devise': 'Breakdown by Currency',
    'Comptes en devise étrangère': 'Foreign currency accounts',
    'Comptes Incomplets': 'Incomplete accounts',
    'Comptes PM en devise': 'LE foreign currency accounts',
    'Comptes PM Incomplets': 'Incomplete LE accounts',
    'Non renseigné': 'Not provided',
    'Non renseignée': 'Not provided',
    'Valide': 'Validated',
    'Rejete': 'Rejected',
    'A valider': 'To validate',
    'Valider': 'Validate',
    'Rejeter': 'Reject',
    'A traiter': 'To process',
    'Validees': 'Validated',
    'Rejetees': 'Rejected',
    'Resultats partiels': 'Partial results',
    'Seuls les': 'Only the',
    'documents les plus recents ont ete analyses sur': 'most recent documents were analysed out of',
    'Affinez le filtre (lot, type) pour tout couvrir.': 'Refine the filter (batch, type) to cover everything.',
    "L'affichage est limite aux": 'The display is limited to the',
    'meilleures correspondances ; exportez le CSV pour la liste complete.':
        'best matches; export the CSV for the full list.',
    'Automatique (lot mixte)': 'Automatic (mixed batch)',
    'En mode automatique, chaque fichier du lot est classe individuellement (CNI, passeport...) selon les types configures.':
        'In automatic mode, each file in the batch is classified individually (ID card, passport...) using the configured types.',
    'Repartition par type': 'Breakdown by type',
    'Corriger le type': 'Correct the type',
    'Type non reconnu': 'Unrecognised type',
    'Ignorer les doublons': 'Skip duplicates',
    'Les fichiers strictement identiques a un document deja charge seront ignores.':
        'Files strictly identical to an already uploaded document will be skipped.',
    'Analyse OCR en arriere-plan': 'OCR analysis in background',
    'En attente du worker OCR...': 'Waiting for the OCR worker...',
    'en attente': 'pending',
    'traites': 'processed',
    'echecs': 'failed',
    'Relancer OCR des echecs': 'Retry failed OCR',
    'Clients non scores': 'Unscored clients',
    'Non Scorés (Échus)': 'Unscored (Overdue)',
    'Échus': 'Overdue',
    'client': 'client',
    'sans classe de risque': 'without risk class',
}

                                                                        
                                                                            
GLOSSARY['kyc_field_codes'] = {
    'CLIENT': 'Client',
    'EXPL': 'Officer',
    'FILIALE': 'Subsidiary',
    'AGENCE': 'Branch',
    'LIB_AGENCE': 'Branch name',
    'PAYNAIS': 'Country of birth',
    'PROFESSION': 'Occupation',
    'SALAIRE': 'Salary',
    'NUMID': 'ID number',
    'TEL': 'Phone',
    'DATNAIS': 'Date of birth',
    'ADRESSE': 'Address',
    'DATVALID': 'Expiry date',
    'ORIGINE_REV': 'Income source',
    'INTITULE_COMPTE': 'Account name',
    'EMPLOYEUR': 'Employer',
    'PAYS_RESID': 'Country of residence',
    'LIEU_DELIVRANCE_CIN': 'ID issue place',
    'BOITE_POSTALE': 'PO box',
    'DATOUV': 'Opening date',
    'DEVISE': 'Currency',
    'RESID': 'Residence',
    'DATEREV': 'Review date',
    'RISQUE': 'Risk',
    'CAPITAL': 'Share capital',
    'CA': 'Turnover',
    'RESULTAT': 'Net income',
    'RCSNO': 'Trade register no.',
    'ADRESSE_SOCIALE': 'Registered address',
    'NUMERO_FISCAL': 'Tax number',
    'PAYS_JUR': 'Country of jurisdiction',
    'ACTIONNAIRE': 'Shareholder',
    'MANDATAIRE': 'Authorised representative',
}


class Command(BaseCommand):
    help = "Pré-remplit le glossaire de traduction FR → EN."

    def add_arguments(self, parser):
        parser.add_argument("--force", action="store_true",
                            help="Réécrit aussi l'anglais des termes déjà présents.")

    def handle(self, *args, **options):
        from kyc.models import TermTranslation
        force = options.get("force")
        created = updated = kept = 0
        for terms in GLOSSARY.values():
            for fr, en in terms.items():
                obj, is_created = TermTranslation.objects.get_or_create(
                    terme_fr=fr, defaults={'terme_en': en})
                if is_created:
                    created += 1
                elif force and obj.terme_en != en:
                    obj.terme_en = en
                    obj.save()
                    updated += 1
                else:
                    kept += 1
        from django.core.cache import cache
        cache.delete('term_glossary_en')
        self.stdout.write(self.style.SUCCESS(
            f"Glossaire : {created} créés, {updated} mis à jour, {kept} conservés."))
