# Generated by Django 5.2.16 on 2026-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilev',
            name='filiale',
            field=models.CharField(choices=[('BOA NE', 'BOA NE'), ('BOA CI', 'BOA CI'), ('BOA TG', 'BOA TG'), ('BOA SN', 'BOA SN'), ('BOA ML', 'BOA ML'), ('BOA BF', 'BOA BF'), ('BOA BJ', 'BOA BJ'), ('BOA CD', 'BOA CD'), ('CG', 'CG'), ('BCB', 'BCB'), ('BOA MR', 'BOA MR'), ('BOA MG', 'BOA MG'), ('BOA UG', 'BOA UG'), ('BOA TZ', 'BOA TZ'), ('BOA RW', 'BOA RW'), ('BOA KE', 'BOA KE'), ('BOA FR', 'BOA FR'), ('BOA KM', 'BOA KM'), ('BOA GH', 'BOA GH'), ('BOA Group', 'BOA Group')], default='BOA Group', max_length=10),
        ),
        migrations.AlterField(
            model_name='zone',
            name='filiale',
            field=models.CharField(choices=[('BOA NE', 'BOA NE'), ('BOA CI', 'BOA CI'), ('BOA TG', 'BOA TG'), ('BOA SN', 'BOA SN'), ('BOA ML', 'BOA ML'), ('BOA BF', 'BOA BF'), ('BOA BJ', 'BOA BJ'), ('BOA CD', 'BOA CD'), ('CG', 'CG'), ('BCB', 'BCB'), ('BOA MR', 'BOA MR'), ('BOA MG', 'BOA MG'), ('BOA UG', 'BOA UG'), ('BOA TZ', 'BOA TZ'), ('BOA RW', 'BOA RW'), ('BOA KE', 'BOA KE'), ('BOA FR', 'BOA FR'), ('BOA KM', 'BOA KM'), ('BOA GH', 'BOA GH'), ('BOA Group', 'BOA Group')], default='BOA Group', max_length=10),
        ),
    ]
