"""
Django settings for buurchange project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import environ
                                                                        
from pathlib import Path

import kyc

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR / "Fiabilisation_kyc" / ".env"))

                                                              
                                                                        

                                                                  
SECRET_KEY = '1nd+ac&2^q)078cepqux_zl+^yz*!^qs08-bsmzo@5ag1rs85i'

                                                                 
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', '10.170.82.20', 'localhost', '0.0.0.0', 'kyc.of.africa']

CSRF_TRUSTED_ORIGINS = [
    "https://kyc.of.africa",
    "https://kyc.of.africa:8444",

]

                        

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_tailwind',
    'kyc',
    'accounts',
    'tailwind',
    'theme',
    'django_countries',

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'Fiabilisation_kyc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fiabilisation_kyc.wsgi.application'

          
                                                                

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'kyc_notation',
        'HOST': '10.170.83.20',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no;',
        },
    }
}

                     
                                                                               

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

                      
                                                     

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

                                        
                                                            

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = '/'                                    

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
AUTH_USER_MODEL = 'accounts.ProfileV'
TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = [
    "127.0.0.1", "10.170.82.20", "0.0.0.0"
]

                                 
DFS_BASE_TEMPLATE = 'base.html'
DFS_CURRENCY_LOCALE = 'fr_fr'

NPM_BIN_PATH = "C://Program Files//nodejs//node"