"""
Django settings for buurchange project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import environ
import time
                                                                        
from pathlib import Path

import kyc

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR / "Fiabilisation_kyc" / ".env"))

                                                         
 
                                                                        
                                                                   
                                                                         
                                                                        
                                                             
 
                                                                                  
_cache_url = env("CACHE_URL", default="")
if _cache_url.startswith(("redis://", "rediss://", "unix://")):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _cache_url,
            "TIMEOUT": 60 * 60 * 24,
                                                                               
                                                                              
                                                                                   
            "KEY_PREFIX": env("CACHE_KEY_PREFIX", default="kyc"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                                                                             
                                                              
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }
                                                                                            
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = False
else:
    CACHES = {
        "default": {
            "BACKEND": env(
                "DJANGO_CACHE_BACKEND",
                default="django.core.cache.backends.filebased.FileBasedCache",
            ),
            "LOCATION": env("DJANGO_CACHE_LOCATION", default=str(BASE_DIR / ".django_cache")),
            "TIMEOUT": 60 * 60 * 24,
            "OPTIONS": {
                "MAX_ENTRIES": 20000,
            },
        }
    }

                                                              
                                                                        

                                                                              
                                                                    
SECRET_KEY = env('SECRET_KEY')

                                               
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
CSRF_TRUSTED_ORIGINS = [
    "https://kyc-test.of.africa",
    "https://kyc-test.of.africa:8444",

]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

                                                                               
                                                                               
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)

                                                                      
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

                                                             
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_HTTPONLY = True

                                  
SESSION_COOKIE_AGE = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

                                    
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

                        

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_tailwind',
    'kyc',
    'accounts',
    'tailwind',
    'theme',
    'django_countries',
                            
    'axes',
                                                                
    'constance',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
                                                                          
                                              
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
                                                                       
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
                                                    
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
                                                         
]

ROOT_URLCONF = 'Fiabilisation_kyc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kyc.context_processors.user_stat_processor',
                'kyc.context_processors.user_filiale_processor',
                'kyc.context_processors.user_filiale_oc_processor',
                'kyc.context_processors.user_groupe_processor',
                'kyc.context_processors.notation',
                'kyc.context_processors.context_conformite_processor',
                'kyc.context_processors.static_version_processor',
                'kyc.context_processors.kyc_display_fields_processor',
                'kyc.context_processors.module_screening_processor',
                'kyc.context_processors.sidebar_access_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fiabilisation_kyc.wsgi.application'

          
                                                                

               
                 
                           
                                
                                
                        
                     
                                                       
                                                           
           
      
   
 


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',                                                              
        'OPTIONS': {
                                                                               
                                                                                   
            'timeout': 60,
        },
    },
                                                                                    
    'prod': {
        'ENGINE': 'mssql',
        'NAME': 'kyc_notation',
        'HOST': '10.170.83.20',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;',
        },
    },
}

                     
                                                                               

AUTH_PASSWORD_VALIDATORS = [
    {
                                                                     
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
                                                  
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
                                                                        
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
                                                         
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

                      
                                                     

LANGUAGE_CODE = 'fr-fr'

                                                          
LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]
                                    
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

                                        
                                                            


STATIC_URL = '/static/'
                                                                                        
                                                                     
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "theme/static"),                                    
]

                                                                             
                                                                                             
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGOUT_REDIRECT_URL = "/login_kyc"
LOGIN_URL = '/login_kyc/'                                    

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
AUTH_USER_MODEL = 'accounts.ProfileV'
TAILWIND_APP_NAME = "theme"
                                                                               
                                                   
INTERNAL_IPS = [
    "127.0.0.1", "10.170.82.20",
]

                                 
DFS_BASE_TEMPLATE = 'base.html'
DFS_CURRENCY_LOCALE = 'fr_fr'

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

                                                                               
STATIC_VERSION = env("ASSET_VERSION", default=str(int(time.time())))

                                                                               
AUTHENTICATION_BACKENDS = [
                                                                               
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

                                                                               
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_CONFIG = {
    'AXES_FAILURE_LIMIT': (
        5, "Nombre de tentatives échouées avant verrouillage du compte", int),
    'AXES_COOLOFF_HOURS': (
        1, "Durée du verrouillage temporaire (en heures)", int),
}

                                                                               
                                                                          
def _axes_failure_limit(request=None, credentials=None):
    from constance import config
    return config.AXES_FAILURE_LIMIT

def _axes_cooloff_time(request=None, credentials=None):
    from datetime import timedelta
    from constance import config
    return timedelta(hours=config.AXES_COOLOFF_HOURS)

AXES_FAILURE_LIMIT = _axes_failure_limit                                           
AXES_COOLOFF_TIME = _axes_cooloff_time                                        
AXES_LOCKOUT_TEMPLATE = 'accounts/lockout.html'
AXES_RESET_ON_SUCCESS = True                                                  
AXES_ENABLED = False

                                                                               
                                                                         
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 1024 * 1024 * 10,         
            'backupCount': 5,
            'formatter': 'verbose',
        },
                                                                               
                                                                            
                                                                            
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
                                                                               
                                                                             
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
                                                                            
        'kyc': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


