"""
Django settings for buurchange project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import environ
import time
# Build paths inside the project like this: os.path .join(BASE_DIR, ...)
from pathlib import Path

import kyc

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR / "Fiabilisation_kyc" / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1nd+ac&2^q)078cepqux_zl+^yz*!^qs08-bsmzo@5ag1rs85i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', '10.170.82.22', 'localhost', '0.0.0.0', 'kyc-test.of.africa', "kyc-test.of.africa:8444"]
CSRF_TRUSTED_ORIGINS = [
    "https://kyc-test.of.africa",
    "https://kyc-test.of.africa:8444",

]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_tailwind',
    'kyc',
    'accounts',
    'tailwind',
    'theme',
    'django_countries',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'Fiabilisation_kyc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kyc.context_processors.user_stat_processor',
                'kyc.context_processors.user_filiale_processor',
                'kyc.context_processors.user_filiale_oc_processor',
                'kyc.context_processors.user_groupe_processor',
                'kyc.context_processors.notation',
                'kyc.context_processors.context_conformite_processor',
                'kyc.context_processors.static_version_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fiabilisation_kyc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'kyc_notation',
#        'HOST': '10.170.83.20',
#        'PORT': '1433',
#        'OPTIONS': {
#            'driver': 'ODBC Driver 17 for SQL Server',
#            'extra_params': 'TrustServerCertificate=yes;',
#        },
#    }
# }
#


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # ou un chemin vers un autre fichier .sqlite3 si tu prÃ©fÃ¨res
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [  # ton dossier principal
    os.path.join(BASE_DIR, "theme/static"),  # le dossier de ton app
]

LOGOUT_REDIRECT_URL = "/login_kyc"
LOGIN_URL = '/login_kyc/'  # L'URL de votre page de connexion

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
AUTH_USER_MODEL = 'accounts.ProfileV'
TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = [
    "127.0.0.1", "10.170.82.20", "0.0.0.0"
]

# Specify your base template file
DFS_BASE_TEMPLATE = 'base.html'
DFS_CURRENCY_LOCALE = 'fr_fr'

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# Cache-busting version for static assets (override with ASSET_VERSION in .env)
STATIC_VERSION = env("ASSET_VERSION", default=str(int(time.time())))

