# Generated by Django 5.2.4 on 2026-04-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_daterev_unique_client_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TAUX_FILIALE',
        ),
    ]
