# Generated by Django 4.2.20 on 2026-05-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_dataqualityrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataqualityrule',
            options={},
        ),
        migrations.AddField(
            model_name='kyc_pp',
            name='DATNAIS',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dataqualityrule',
            name='control_type',
            field=models.CharField(choices=[('codape_agec_match', 'Correspondance CODAPE / AGEC'), ('composite', 'Règle composite (multi-critères)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dataqualityrule',
            name='field_name',
            field=models.CharField(choices=[('CODAPE', 'CODAPE'), ('IDP', 'IDP'), ('PAYNAIS', 'PAYNAIS'), ('PROFESSION', 'PROFESSION'), ('ADRESSE', 'ADRESSE'), ('PAYS_RESID', 'PAYS_RESID'), ('NUMID', 'NUMID'), ('SALAIRE', 'SALAIRE'), ('DATVALID', 'DATVALID'), ('DATNAIS', 'DATNAIS'), ('TEL', 'TEL'), ('DATOUV', 'DATOUV'), ('PPE', 'PPE'), ('DEVISE', 'DEVISE'), ('RESID', 'RESID'), ('CODAPE', 'CODAPE'), ('AGEC', 'AGEC'), ('IDM', 'IDM'), ('RCSNO', 'RCSNO'), ('CAPITAL', 'CAPITAL'), ('CA', 'CA'), ('DATOUV', 'DATOUV'), ('TEL', 'TEL'), ('DEVISE', 'DEVISE'), ('RESID', 'RESID')], max_length=100),
        ),
        migrations.CreateModel(
            name='DataQualityCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('CODAPE', 'CODAPE'), ('IDP', 'IDP'), ('PAYNAIS', 'PAYNAIS'), ('PROFESSION', 'PROFESSION'), ('ADRESSE', 'ADRESSE'), ('PAYS_RESID', 'PAYS_RESID'), ('NUMID', 'NUMID'), ('SALAIRE', 'SALAIRE'), ('DATVALID', 'DATVALID'), ('DATNAIS', 'DATNAIS'), ('TEL', 'TEL'), ('DATOUV', 'DATOUV'), ('PPE', 'PPE'), ('DEVISE', 'DEVISE'), ('RESID', 'RESID'), ('CODAPE', 'CODAPE'), ('AGEC', 'AGEC'), ('IDM', 'IDM'), ('RCSNO', 'RCSNO'), ('CAPITAL', 'CAPITAL'), ('CA', 'CA'), ('DATOUV', 'DATOUV'), ('TEL', 'TEL'), ('DEVISE', 'DEVISE'), ('RESID', 'RESID')], max_length=100)),
                ('operator', models.CharField(choices=[('=', 'Égal à (=)'), ('!=', 'Différent de (!=)'), ('>', 'Supérieur à (>)'), ('<', 'Inférieur à (<)'), ('>=', 'Supérieur ou égal (>=)'), ('<=', 'Inférieur ou égal (<=)'), ('contains', 'Contient'), ('regex', 'Expression régulière'), ('is_empty', 'Est vide'), ('is_not_empty', "N'est pas vide"), ('expired', "Est expiré (Date < Aujourd'hui)"), ('age_gt', 'Âge supérieur à'), ('age_lt', 'Âge inférieur à')], max_length=20)),
                ('value', models.CharField(blank=True, help_text="Valeur fixe ou nom d'un autre champ", max_length=255, null=True)),
                ('is_field_comparison', models.BooleanField(default=False, help_text="Comparer avec un autre champ au lieu d'une valeur fixe")),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='kyc.dataqualityrule')),
            ],
        ),
    ]
