# Generated by Django 4.2.20 on 2026-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_dataqualityrule_control_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataqualitycondition',
            name='is_field_comparison',
        ),
        migrations.AlterField(
            model_name='dataqualitycondition',
            name='operator',
            field=models.CharField(choices=[('=', 'Égal à (=)'), ('!=', 'Différent de (!=)'), ('>', 'Supérieur à (>)'), ('<', 'Inférieur à (<)'), ('>=', 'Supérieur ou égal (>=)'), ('<=', 'Inférieur ou égal (<=)'), ('contains', 'Contient'), ('regex', 'Expression régulière'), ('is_empty', 'Est vide'), ('is_not_empty', "N'est pas vide"), ('expired', "Est expiré (Date < Aujourd'hui)"), ('age_gt', 'Âge supérieur à'), ('age_lt', 'Âge inférieur à'), ('min_length', 'Longueur minimum'), ('max_length', 'Longueur maximum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dataqualitycondition',
            name='value',
            field=models.CharField(blank=True, help_text='Valeur fixe', max_length=255, null=True),
        ),
    ]
