# Generated by Django 4.2.20 on 2026-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_kycdocumentextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocumentextraction',
            name='import_batch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='kycdocumentextraction',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocumentextraction',
            name='page_range',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='kycdocumentextraction',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='kycdocumentextraction',
            index=models.Index(fields=['import_batch'], name='kyc_kycdocu_import__49fefd_idx'),
        ),
    ]
