# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_kycdocumentextraction_origine_revenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocumentextraction',
            name='pays_delivrance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='kycdocumentextraction',
            index=models.Index(fields=['pays_delivrance'], name='kyc_kycdocu_pays_de_20d3a5_idx'),
        ),
    ]
