# Generated by Django 4.2.20 on 2026-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0013_kycdocumentmatchsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='birth_place_weight',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Poids lieu de naissance'),
        ),
    ]
