from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0018_kycdocumentmatchjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualitycondition",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("INTITULE_COMPTE", "INTITULE_COMPTE"),
                    ("CODAPE", "CODAPE"),
                    ("IDP", "IDP"),
                    ("PAYNAIS", "PAYNAIS"),
                    ("PROFESSION", "PROFESSION"),
                    ("EMPLOYEUR", "EMPLOYEUR"),
                    ("ADRESSE", "ADRESSE"),
                    ("PAYS_RESID", "PAYS_RESID"),
                    ("LIEU_DELIVRANCE_CIN", "LIEU_DELIVRANCE_CIN"),
                    ("BOITE_POSTALE", "BOITE_POSTALE"),
                    ("CONSENT_BIC", "CONSENT_BIC"),
                    ("NUMID", "NUMID"),
                    ("SALAIRE", "SALAIRE"),
                    ("DATVALID", "DATVALID"),
                    ("DATNAIS", "DATNAIS"),
                    ("TEL", "TEL"),
                    ("DATOUV", "DATOUV"),
                    ("PPE", "PPE"),
                    ("DEVISE", "DEVISE"),
                    ("RESID", "RESID"),
                    ("INTITULE_COMPTE", "INTITULE_COMPTE"),
                    ("CODAPE", "CODAPE"),
                    ("AGEC", "AGEC"),
                    ("IDM", "IDM"),
                    ("RCSNO", "RCSNO"),
                    ("ADRESSE_SOCIALE", "ADRESSE_SOCIALE"),
                    ("NUMERO_FISCAL", "NUMERO_FISCAL"),
                    ("PAYS_JUR", "PAYS_JUR"),
                    ("ACTIONNAIRE", "ACTIONNAIRE"),
                    ("MANDATAIRE", "MANDATAIRE"),
                    ("BOITE_POSTALE", "BOITE_POSTALE"),
                    ("CONSENT_BIC", "CONSENT_BIC"),
                    ("CAPITAL", "CAPITAL"),
                    ("CA", "CA"),
                    ("DATOUV", "DATOUV"),
                    ("TEL", "TEL"),
                    ("DEVISE", "DEVISE"),
                    ("RESID", "RESID"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityrule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("INTITULE_COMPTE", "INTITULE_COMPTE"),
                    ("CODAPE", "CODAPE"),
                    ("IDP", "IDP"),
                    ("PAYNAIS", "PAYNAIS"),
                    ("PROFESSION", "PROFESSION"),
                    ("EMPLOYEUR", "EMPLOYEUR"),
                    ("ADRESSE", "ADRESSE"),
                    ("PAYS_RESID", "PAYS_RESID"),
                    ("LIEU_DELIVRANCE_CIN", "LIEU_DELIVRANCE_CIN"),
                    ("BOITE_POSTALE", "BOITE_POSTALE"),
                    ("CONSENT_BIC", "CONSENT_BIC"),
                    ("NUMID", "NUMID"),
                    ("SALAIRE", "SALAIRE"),
                    ("DATVALID", "DATVALID"),
                    ("DATNAIS", "DATNAIS"),
                    ("TEL", "TEL"),
                    ("DATOUV", "DATOUV"),
                    ("PPE", "PPE"),
                    ("DEVISE", "DEVISE"),
                    ("RESID", "RESID"),
                    ("INTITULE_COMPTE", "INTITULE_COMPTE"),
                    ("CODAPE", "CODAPE"),
                    ("AGEC", "AGEC"),
                    ("IDM", "IDM"),
                    ("RCSNO", "RCSNO"),
                    ("ADRESSE_SOCIALE", "ADRESSE_SOCIALE"),
                    ("NUMERO_FISCAL", "NUMERO_FISCAL"),
                    ("PAYS_JUR", "PAYS_JUR"),
                    ("ACTIONNAIRE", "ACTIONNAIRE"),
                    ("MANDATAIRE", "MANDATAIRE"),
                    ("BOITE_POSTALE", "BOITE_POSTALE"),
                    ("CONSENT_BIC", "CONSENT_BIC"),
                    ("CAPITAL", "CAPITAL"),
                    ("CA", "CA"),
                    ("DATOUV", "DATOUV"),
                    ("TEL", "TEL"),
                    ("DEVISE", "DEVISE"),
                    ("RESID", "RESID"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="ACTIONNAIRE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="ADRESSE_SOCIALE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="BOITE_POSTALE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="CONSENT_BIC",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="INTITULE_COMPTE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="MANDATAIRE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="NUMERO_FISCAL",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pm",
            name="PAYS_JUR",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pp",
            name="BOITE_POSTALE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pp",
            name="CONSENT_BIC",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pp",
            name="EMPLOYEUR",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pp",
            name="INTITULE_COMPTE",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="kyc_pp",
            name="LIEU_DELIVRANCE_CIN",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
