# Generated by Django 4.2.20 on 2026-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0029_kycfieldvisibilityconfig_filiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code technique')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé affiché')),
                ('keywords', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules')),
                ('min_score', models.FloatField(default=2.0, help_text='Score minimum pour être détecté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
