# Generated by Django 4.2.20 on 2026-06-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0032_alter_kycdocumenttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycfieldvisibilityconfig',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
