# Generated by Django 4.2.20 on 2026-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0033_kycfieldvisibilityconfig_field_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_pm',
            name='CLIENT',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kyc_pp',
            name='CLIENT',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
