# Generated by Django 4.2.20 on 2026-06-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0037_emailreminderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppreciationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demarrage', models.DateField(help_text='Le trimestre courant = nombre de trimestres écoulés depuis cette date + 1 (plafonné à 4).', verbose_name='Date de démarrage de la campagne')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Appréciation globale',
                'verbose_name_plural': 'Configuration Appréciation globale',
            },
        ),
        migrations.CreateModel(
            name='Appreciation_globale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiale', models.CharField(blank=True, max_length=50)),
                ('expl', models.CharField(blank=True, max_length=50)),
                ('trimestre', models.IntegerField(default=1)),
                ('taux_evolution', models.FloatField(blank=True, null=True, verbose_name="Taux d'évolution (flux, moy. PP+PM)")),
                ('taux_qualite', models.FloatField(blank=True, null=True, verbose_name='Taux de qualité agent')),
                ('notation', models.CharField(blank=True, max_length=20, verbose_name='Notation flux retenue')),
                ('appreciation_qualite', models.CharField(blank=True, max_length=30)),
                ('appreciation_globale', models.CharField(blank=True, max_length=20)),
                ('mesure', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appreciations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appréciation globale',
                'verbose_name_plural': 'Appréciations globales',
                'ordering': ['filiale', 'expl'],
                'unique_together': {('filiale', 'expl')},
            },
        ),
    ]
