# Generated by Django 4.2.20 on 2026-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0038_appreciationconfig_appreciation_globale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreciationconfig',
            options={'verbose_name': 'Configuration Appréciation globale', 'verbose_name_plural': 'Configurations Appréciation globale (par filiale)'},
        ),
        migrations.AddField(
            model_name='appreciationconfig',
            name='filiale',
            field=models.CharField(default='', help_text='Code de la filiale (ex. « BOA TG »). Une seule configuration possible par filiale.', max_length=50, unique=True, verbose_name='Filiale'),
        ),
    ]
