# Generated by Django 4.2.20 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0041_emailreminderconfig_notify_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme_fr', models.CharField(help_text="Texte français exact tel qu'affiché (ex. « Taux de complétude »).", max_length=300, unique=True, verbose_name='Terme (français)')),
                ('terme_en', models.CharField(max_length=300, verbose_name='Équivalence (anglais)')),
                ('domaine', models.CharField(choices=[('general', 'Général'), ('banque', 'Banque'), ('finance', 'Finance'), ('conformite', 'Conformité / KYC'), ('interface', 'Interface / UI')], default='general', max_length=20, verbose_name='Domaine')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Note / contexte')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traduction de terme (glossaire)',
                'verbose_name_plural': 'Glossaire des traductions FR → EN',
                'ordering': ['domaine', 'terme_fr'],
            },
        ),
    ]
