# Generated by Django 5.2.4 on 2026-07-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0048_kycdocumentmatchsettings_min_display_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycMatchValidatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organe', models.CharField(choices=[('Directeur Agence', 'Directeur Agence'), ('Directeur de Zone', 'Directeur de Zone'), ('Chargé Client', 'Chargé Client'), ('Contrôle Permanent', 'Contrôle Permanent'), ('Directeur Réseau', 'Directeur Réseau'), ('Contrôle Permanent Groupe', 'Contrôle Permanent Groupe'), ('Conformité', 'Conformité'), ('Conformité Groupe', 'Conformité Groupe'), ('PASS', 'PASS'), ('DSI', 'DSI'), ('GUEST', 'GUEST'), ('Qualité', 'Qualité'), ('DAI', 'DAI'), ('Risques', 'Risques')], max_length=50, unique=True, verbose_name='Organe autorise')),
                ('can_validate', models.BooleanField(default=True, verbose_name='Peut valider')),
                ('can_reject', models.BooleanField(default=True, verbose_name='Peut rejeter')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil validateur (correspondances KYC ID)',
                'verbose_name_plural': 'Profils validateurs (correspondances KYC ID)',
                'ordering': ['organe'],
            },
        ),
        migrations.CreateModel(
            name='KycMatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('pp', 'Particuliers (PP)'), ('pm', 'Entreprises (PM)')], default='pp', max_length=10)),
                ('client_id', models.PositiveIntegerField(help_text='PK du client Kyc_pp / Kyc_pm concerne.')),
                ('client_code', models.CharField(blank=True, default='', max_length=200)),
                ('filiale', models.CharField(blank=True, default='', max_length=200)),
                ('agence', models.CharField(blank=True, default='', max_length=200)),
                ('match_rate', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'A valider'), ('validated', 'Valide'), ('rejected', 'Rejete')], db_index=True, default='validated', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_decisions', to='kyc.kycdocumentextraction')),
            ],
            options={
                'verbose_name': 'Decision de correspondance KYC ID',
                'verbose_name_plural': 'Decisions de correspondance KYC ID',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='kyc_kycmatc_status_4bde5e_idx'), models.Index(fields=['client_type', 'client_id'], name='kyc_kycmatc_client__38b64c_idx'), models.Index(fields=['filiale', 'agence'], name='kyc_kycmatc_filiale_e5fb0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'client_type', 'client_id'), name='unique_kyc_match_decision')],
            },
        ),
    ]
