# Generated by Django 5.2.4 on 2026-07-03 15:51

from django.db import migrations

# Profils autorises par defaut a valider/rejeter les correspondances KYC ID.
# Modifiables ensuite dans l'admin (Profils validateurs).
DEFAULT_VALIDATOR_ORGANES = [
    "Conformité",
    "Conformité Groupe",
    "Contrôle Permanent",
    "Contrôle Permanent Groupe",
    "PASS",
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model("kyc", "KycMatchValidatorRole")
    for organe in DEFAULT_VALIDATOR_ORGANES:
        Role.objects.get_or_create(organe=organe, defaults={"can_validate": True, "can_reject": True})


def unseed_roles(apps, schema_editor):
    Role = apps.get_model("kyc", "KycMatchValidatorRole")
    Role.objects.filter(organe__in=DEFAULT_VALIDATOR_ORGANES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0049_kycmatchvalidatorrole_kycmatchdecision'),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
