# Generated by Django 5.2.4 on 2026-07-03 16:03

from django.db import migrations

DEFAULT_TYPES = [
    {
        "code": "piece_identite",
        "label": "Pièce d'identité",
        "keywords": "CARTE NATIONALE, CARTE D'IDENTITE, CNI, IDENTITY CARD, NATIONAL ID, NIN, NPI, EID NUMBER, CARD NUMBER",
        "min_score": 2.0,
    },
    {
        "code": "passeport",
        "label": "Passeport",
        "keywords": "PASSEPORT, PASSPORT, N° PASSEPORT, PASSPORT NO, PASSPORT NUMBER",
        "min_score": 2.0,
    },
]


def seed_types(apps, schema_editor):
    KycDocumentType = apps.get_model("kyc", "KycDocumentType")
    for spec in DEFAULT_TYPES:
        KycDocumentType.objects.get_or_create(
            code=spec["code"], filiale="", client_type="pp",
            defaults={"label": spec["label"], "keywords": spec["keywords"], "min_score": spec["min_score"]},
        )


def unseed_types(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0052_remove_kycdocumentmatchsettings_firstname_weight_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_types, unseed_types),
    ]
