# Generated by Django 5.2.4 on 2026-07-03 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0053_seed_default_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocumentmatchsettings',
            name='birth_date_weight',
        ),
        migrations.RemoveField(
            model_name='kycdocumentmatchsettings',
            name='birth_place_weight',
        ),
        migrations.RemoveField(
            model_name='kycdocumentmatchsettings',
            name='document_validity_weight',
        ),
        migrations.RemoveField(
            model_name='kycdocumentmatchsettings',
            name='fullname_weight',
        ),
        migrations.RemoveField(
            model_name='kycdocumentmatchsettings',
            name='nationality_weight',
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pm_address_weight',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PM · Poids adresse sociale'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pm_country_weight',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PM · Poids pays de creation (PAYS_JUR)'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pm_fiscal_weight',
            field=models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PM · Poids numero fiscal'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pm_fullname_weight',
            field=models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PM · Poids raison sociale'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pp_birth_country_weight',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PP · Poids pays de naissance'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pp_birth_date_weight',
            field=models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PP · Poids date de naissance'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pp_birth_place_weight',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PP · Poids lieu de naissance'),
        ),
        migrations.AddField(
            model_name='kycdocumentmatchsettings',
            name='pp_fullname_weight',
            field=models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='PP · Poids nom & prenom'),
        ),
        migrations.AlterField(
            model_name='kycdocumentmatchsettings',
            name='pm_fullname_field',
            field=models.CharField(choices=[('INTITULE_COMPTE', 'INTITULE_COMPTE (Raison sociale / Denomination)'), ('ACTIONNAIRE', 'ACTIONNAIRE (Actionnaire)'), ('MANDATAIRE', 'MANDATAIRE (Mandataire)')], default='INTITULE_COMPTE', max_length=50, verbose_name='Champ raison sociale (KYC PM)'),
        ),
    ]
