# Generated by Django 4.2.20 on 2026-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0056_tauxqualite_kyc_pp_kyc_pp_scope_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycScreeningAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organe', models.CharField(choices=[('Directeur Agence', 'Directeur Agence'), ('Directeur de Zone', 'Directeur de Zone'), ('Chargé Client', 'Chargé Client'), ('Contrôle Permanent', 'Contrôle Permanent'), ('Directeur Réseau', 'Directeur Réseau'), ('Contrôle Permanent Groupe', 'Contrôle Permanent Groupe'), ('Conformité', 'Conformité'), ('Conformité Groupe', 'Conformité Groupe'), ('PASS', 'PASS'), ('DSI', 'DSI'), ('GUEST', 'GUEST'), ('Qualité', 'Qualité'), ('DAI', 'DAI'), ('Risques', 'Risques')], max_length=50, unique=True, verbose_name='Organe')),
                ('tab_charger', models.BooleanField(default=False, verbose_name='Onglet Charger')),
                ('tab_suivi', models.BooleanField(default=False, verbose_name='Onglet Suivi')),
                ('tab_resultats', models.BooleanField(default=True, verbose_name='Onglet Resultats')),
                ('tab_sources', models.BooleanField(default=False, verbose_name='Onglet Sources par champ')),
                ('tab_documents', models.BooleanField(default=True, verbose_name='Onglet Documents extraits')),
                ('can_upload_batches', models.BooleanField(default=False, verbose_name='Peut charger des lots')),
                ('can_run_matching', models.BooleanField(default=False, verbose_name='Peut lancer le rapprochement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acces Screening KYC ID (par organe)',
                'verbose_name_plural': 'Acces Screening KYC ID (par organe)',
                'ordering': ['organe'],
            },
        ),
    ]
