# Generated by Django 4.2.20 on 2026-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0058_seed_screening_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycfieldvisibilityconfig',
            name='field_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
