# Generated by Django 4.2.20 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0059_kycfieldvisibilityconfig_field_labels'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kyc_pm',
            index=models.Index(fields=['FILIALE', 'AGENCE', 'EXPL'], name='kyc_pm_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='kyc_pm',
            index=models.Index(fields=['DATEREV'], name='kyc_pm_daterev_idx'),
        ),
        migrations.AddIndex(
            model_name='kyc_pm',
            index=models.Index(fields=['RISQUE'], name='kyc_pm_risque_idx'),
        ),
        migrations.AddIndex(
            model_name='kyc_pp',
            index=models.Index(fields=['DATEREV'], name='kyc_pp_daterev_idx'),
        ),
        migrations.AddIndex(
            model_name='kyc_pp',
            index=models.Index(fields=['RISQUE'], name='kyc_pp_risque_idx'),
        ),
        migrations.AddIndex(
            model_name='tauxevolution',
            index=models.Index(fields=['date'], name='tauxevo_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tauxevolution',
            index=models.Index(fields=['filiale', 'flux_stock', 'expl'], name='tauxevo_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='tauxevolution_filiale',
            index=models.Index(fields=['filiale', 'date'], name='tauxevofil_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='tauxevolution_filiale',
            index=models.Index(fields=['date'], name='tauxevofil_date_idx'),
        ),
    ]
