# Generated by Django 4.2.20 on 2026-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0060_kyc_pm_kyc_pm_scope_idx_kyc_pm_kyc_pm_daterev_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityFluxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux_window', models.CharField(choices=[('veille', 'Dernière journée (DATOUV = hier)'), ('mois', 'Mois précédent (DATOUV dans le mois calendaire précédent)')], default='veille', help_text='Clients comptés dans le flux : DATOUV de la veille, ou du mois calendaire précédent.', max_length=10, verbose_name='Fenêtre du flux')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration flux qualité',
                'verbose_name_plural': 'Configuration flux qualité',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tauxqualite',
            name='uniq_tauxqualite_scope_jour',
        ),
        migrations.AddField(
            model_name='tauxqualite',
            name='flux_stock',
            field=models.CharField(choices=[('stock', 'Stock (toute la base)'), ('flux', 'Flux (nouveaux clients selon DATOUV)')], default='stock', max_length=5),
        ),
        migrations.AddIndex(
            model_name='tauxqualite',
            index=models.Index(fields=['flux_stock', 'date'], name='tauxqualite_flux_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='tauxqualite',
            constraint=models.UniqueConstraint(fields=('filiale', 'agence', 'expl', 'applicability', 'flux_stock', 'date'), name='uniq_tauxqualite_scope_jour'),
        ),
    ]
