# Generated by Django 4.2.20 on 2026-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0069_alter_devise_filiale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_pm',
            name='ACTIONNAIRE',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='kyc_pm',
            name='MANDATAIRE',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
