# Generated by Django 5.2.16 on 2026-09-08 14:44
#
# Suppression du modèle QualityFluxConfig. En prod (MSSQL) la table
# `kyc_qualityfluxconfig` peut ne jamais avoir été créée (migration 0061
# jouée en --fake) : un DROP TABLE sec échouerait avec « Invalid object
# name ». On drope donc la table seulement si elle existe, via
# l'introspection de la connexion (compatible SQLite dev et MSSQL prod).

from django.db import migrations


def drop_table_if_exists(apps, schema_editor):
    table = "kyc_qualityfluxconfig"
    existing = schema_editor.connection.introspection.table_names()
    if table in existing:
        schema_editor.execute(
            schema_editor.sql_delete_table % {"table": schema_editor.quote_name(table)}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0072_appreciation_globale_methode_taux_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='QualityFluxConfig'),
            ],
            database_operations=[
                migrations.RunPython(drop_table_if_exists, migrations.RunPython.noop),
            ],
        ),
    ]
